# TODO: MERGE for outputformats and stuff https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
# TODO: hugo 0.110.0 rename to hugo.toml https://gohugo.io/getting-started/configuration/#hugotoml-vs-configtoml

baseURL = 'http://localhost:1313'
languageCode = 'en-us'
defaultContentLanguage = 'en'

title = "Arno Peters's Blog"
theme = "internet-weblog"  #https://themes.gohugo.io/themes/internet-weblog/
#theme = "papermod" #https://github.com/adityatelange/hugo-PaperMod/wiki/Installation
enableGitInfo = true

# https://themes.gohugo.io/themes/chringel-hugo-theme/ -> auto light/dark device preference


# Only required for non-directory based posts, to access images in redirected static folder. 
#[[module.mounts]]
#source = "content/images"
#target = "assets/images"

# TODO: move goldmark render settings to theme and use shallow merge
[markup]
  [markup.highlight]
    style = 'vs'  # https://xyproto.github.io/splash/docs/
  [markup.goldmark.renderer]
    # for reveal.js - currently only the unsafe mode for goldmark is supported
    unsafe = true  # required for templates and stuff

[imaging]
  #anchor = 'Smart'
  #bgColor = '#ffffff'
  #hint = 'photo'
  quality = 100
  resampleFilter = 'Lanczos'